/*
 * Signals that can be sent to the state module (to update the system state).
 */
export type Signal = 'ready'
            | 'show-component'
            | 'set-current-file-index'
            | 'close-current-file'
            | 'new-program'
            | 'new-skeleton-program'
            | 'save-local'
            | 'save-remote'
            | 'open-remote'
            | 'save-tgx-program'
            | 'set-language'
            | 'set-example'
            | 'load-remote-file'
            | 'set-file'
            | 'set-name'
            | 'set-code'
            | 'toggle-fullscreen'
            | 'toggle-assembler'
            | 'toggle-decimal'
            | 'toggle-show-canvas'
            | 'toggle-show-output'
            | 'toggle-show-memory'
            | 'set-draw-count-max'
            | 'set-code-count-max'
            | 'set-small-size'
            | 'set-stack-size'
            | 'reset-machine-options'
            | 'machine-run-pause'
            | 'machine-halt'
            | 'dump-memory'
