security:
    providers:
        database_users:
            entity:
                class: App:User
                property: username
    encoders:
        App\Entity\User:
            algorithm: auto
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                provider: database_users
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: logout
