twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['_includes/form-layout.html.twig']
    paths:
        '%kernel.project_dir%/public/css': css
        '%kernel.project_dir%/public/images': images
